<?php
require 'config.php';
$type = $_GET['type'] ?? '';
$id = intval($_GET['id'] ?? 0);

// Fetch invoice data
if ($type === 'in') {
    $stmt = $conn->prepare('SELECT pi.id, pi.qty_kg, pi.entry_date, p.name FROM product_in pi JOIN products p ON p.id = pi.product_id WHERE pi.id = ?');
    $stmt->bind_param('i', $id);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $title = 'Stock Entry Invoice';
    $ref = 'IN-' . str_pad($row['id'], 6, '0', STR_PAD_LEFT);
} elseif ($type === 'out') {
    $stmt = $conn->prepare('SELECT po.id, po.qty_kg, po.out_date, po.customer_name, po.customer_mobile, po.customer_address, po.amount, p.name FROM product_out po JOIN products p ON p.id = po.product_id WHERE po.id = ?');
    $stmt->bind_param('i', $id);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $title = 'Dispatch Invoice';
    $ref = 'OUT-' . str_pad($row['id'], 6, '0', STR_PAD_LEFT);
} else {
    echo 'Invalid invoice type.'; exit;
}

// HTML + CSS for compact invoice
$html = '<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>'.htmlspecialchars($title).'</title>
<style>
body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    background:#f9f9f9; margin:0; padding:20px;
    -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none;
}
.inv {
    max-width:600px; margin:0 auto; padding:20px; border-radius:10px; background:#fff;
    box-shadow:0 2px 6px rgba(0,0,0,0.05); position: relative; overflow: hidden; font-size:13px;
}

.inv * { position: relative; z-index:1; }

.header {display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;}
.header img {max-height:50px;}
.header h2 {margin:0; font-size:18px; font-weight:600; color:#222;}
.ref {font-size:12px; color:#666; margin-top:2px;}

table {width:100%; border-collapse:collapse; margin-top:10px; font-size:12px;}
th, td {padding:8px 10px; border-bottom:1px solid #ddd; text-align:left;}
th {font-weight:600; background:#f5f5f5; color:#333; text-transform:uppercase; font-size:11px;}
td {color:#444;}

.footer {margin-top:20px; text-align:center; color:#888; font-size:11px;}
.button-group {text-align:center; margin-top:15px;}
.button-group button {display:inline-block; margin:5px; padding:8px 16px; font-size:13px; background:#444; color:#fff; border:none; border-radius:5px; cursor:pointer;}
.button-group button:hover {background:#222;}
</style>
</head>
<body>
<div class="inv" id="invoice">
  <div class="header">
    <img src="https://www.naturalfarmingspk.com/wp-content/uploads/2025/09/logo.webp" alt="Logo">
    <div>
      <h2>'.htmlspecialchars($title).'</h2>
      <div class="ref">Invoice #: '.htmlspecialchars($ref).'</div>
    </div>
  </div>
  <table>
    <tbody>
      <tr><th>Product</th><td>'.htmlspecialchars($row['name']).'</td></tr>';

if ($type === 'in') {
    $html .= '<tr><th>Date</th><td>'.htmlspecialchars($row['entry_date']).'</td></tr>
              <tr><th>Weight (kg)</th><td>'.(float)$row['qty_kg'].'</td></tr>';
} else {
    $html .= '<tr><th>Date</th><td>'.htmlspecialchars($row['out_date']).'</td></tr>
              <tr><th>Customer</th><td>'.htmlspecialchars($row['customer_name']).'</td></tr>
              <tr><th>Mobile</th><td>'.htmlspecialchars($row['customer_mobile']).'</td></tr>
              <tr><th>Address</th><td>'.nl2br(htmlspecialchars($row['customer_address'])).'</td></tr>
              <tr><th>Weight (kg)</th><td>'.(float)$row['qty_kg'].'</td></tr>
              <tr><th>Amount</th><td>'.htmlspecialchars($row['amount']).'</td></tr>';
}

$html .= '</tbody>
  </table>
  <div class="footer">Generated by HossSystem • www.naturalfarmingspk.com</div>
</div>

<div class="button-group">
  <button onclick="window.print()">Print / Save as PDF</button>
  <button id="savePng">Save as PNG</button>
</div>

<!-- Include html2canvas for PNG capture -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
<script>
document.getElementById("savePng").addEventListener("click", function(){
    html2canvas(document.getElementById("invoice"), {scale:2, useCORS:true}).then(function(canvas){
        var link = document.createElement("a");
        link.download = "invoice-'.$type.'-'.$id.'.png";
        link.href = canvas.toDataURL("image/png");
        link.click();
    });
});
</script>
</body>
</html>';

echo $html;
?>

